CREATE TABLE UsersManaged (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Sub NVARCHAR(255) UNIQUE NOT NULL,
    TenantId UNIQUEIDENTIFIER NOT NULL,
    ApiToken NVARCHAR(255) UNIQUE NOT NULL,
    AccessLevel NVARCHAR(50) NOT NULL DEFAULT 'Free',
    RequestsThisMonth INT NOT NULL DEFAULT 0,
    RequestMonthStart DATETIME2 NOT NULL DEFAULT GETDATE()
);
